// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/features/driver_orders/domain/use_cases/mirror_order_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:track_flowers_app/config/base_response/entity/base_pagination_entity.dart'
    as _i5;
import 'package:track_flowers_app/config/base_response/result.dart' as _i4;
import 'package:track_flowers_app/config/uses_cases/pagination_params.dart'
    as _i7;
import 'package:track_flowers_app/features/driver_orders/domain/entities/order_entity.dart'
    as _i6;
import 'package:track_flowers_app/features/driver_orders/domain/repositories/driver_orders_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DriverOrdersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverOrdersRepository extends _i1.Mock
    implements _i2.DriverOrdersRepository {
  MockDriverOrdersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>>
  getPendingOrders(_i7.PaginationParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOrders, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                  >(this, Invocation.method(#getPendingOrders, [params])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>>);

  @override
  _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>> getMyOrders(
    _i7.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                  >(this, Invocation.method(#getMyOrders, [params])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>>);

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> getActiveOrder() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrder, []),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#getActiveOrder, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> acceptOrder(_i6.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOrder, [order]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#acceptOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> rejectOrder(_i6.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#rejectOrder, [order]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#rejectOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> startOrder(_i6.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [order]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#startOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> completeOrder(
    _i6.OrderEntity? order,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeOrder, [order]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#completeOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);

  @override
  _i3.Future<void> mirrorOrderToFirebase(
    _i6.OrderEntity? order, {
    double? driverLat,
    double? driverLng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mirrorOrderToFirebase,
              [order],
              {#driverLat: driverLat, #driverLng: driverLng},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
