// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdw8PHyJdqvd9ZXFnpFjx2IxQ2DyDpLP0',
    appId: '1:221402846484:android:4162c9c1c40fa71c0d5e01',
    messagingSenderId: '221402846484',
    projectId: 'flower-team5',
    storageBucket: 'flower-team5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbhCMSDAgT75R9BZxcQcA6IB-6GiKU88',
    appId: '1:221402846484:ios:9ca0469fe2ff86980d5e01',
    messagingSenderId: '221402846484',
    projectId: 'flower-team5',
    storageBucket: 'flower-team5.firebasestorage.app',
    iosBundleId: 'com.example.trackFlowersApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0GiIyzN5hUVeKiS1vDmdz3xiY4Lw_JA',
    appId: '1:221402846484:web:794887380f8559e10d5e01',
    messagingSenderId: '221402846484',
    projectId: 'flower-team5',
    authDomain: 'flower-team5.firebaseapp.com',
    storageBucket: 'flower-team5.firebasestorage.app',
    measurementId: 'G-NHYBWNKKDY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbhCMSDAgT75R9BZxcQcA6IB-6GiKU88',
    appId: '1:221402846484:ios:9ca0469fe2ff86980d5e01',
    messagingSenderId: '221402846484',
    projectId: 'flower-team5',
    storageBucket: 'flower-team5.firebasestorage.app',
    iosBundleId: 'com.example.trackFlowersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc0GiIyzN5hUVeKiS1vDmdz3xiY4Lw_JA',
    appId: '1:221402846484:web:4315c03535a935e00d5e01',
    messagingSenderId: '221402846484',
    projectId: 'flower-team5',
    authDomain: 'flower-team5.firebaseapp.com',
    storageBucket: 'flower-team5.firebasestorage.app',
    measurementId: 'G-D0WQV1NXB0',
  );
}
