// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/features/driver_orders/data/repositories/driver_orders_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:track_flowers_app/config/base_response/result.dart' as _i4;
import 'package:track_flowers_app/config/fcm/user_entity.dart' as _i13;
import 'package:track_flowers_app/config/firebase/order_tracking_service.dart'
    as _i12;
import 'package:track_flowers_app/config/uses_cases/pagination_params.dart'
    as _i6;
import 'package:track_flowers_app/features/driver_orders/data/data_sources/driver_orders_remote_data_source_contract.dart'
    as _i2;
import 'package:track_flowers_app/features/driver_orders/data/models/order_model.dart'
    as _i8;
import 'package:track_flowers_app/features/driver_orders/data/models/orders_page_model.dart'
    as _i5;
import 'package:track_flowers_app/features/tracking_test/domain/entities/order_entity.dart'
    as _i11;
import 'package:track_flowers_app/features/tracking_test/domain/entities/user_entity.dart'
    as _i10;
import 'package:track_flowers_app/features/tracking_test/domain/repositories/tracking_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DriverOrdersRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverOrdersRemoteDataSourceContract extends _i1.Mock
    implements _i2.DriverOrdersRemoteDataSourceContract {
  MockDriverOrdersRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.OrdersPageModel>> getPendingOrders(
    _i6.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOrders, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.OrdersPageModel>>.value(
              _i7.dummyValue<_i4.Result<_i5.OrdersPageModel>>(
                this,
                Invocation.method(#getPendingOrders, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.OrdersPageModel>>);

  @override
  _i3.Future<_i4.Result<_i5.OrdersPageModel>> getMyOrders(
    _i6.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.OrdersPageModel>>.value(
              _i7.dummyValue<_i4.Result<_i5.OrdersPageModel>>(
                this,
                Invocation.method(#getMyOrders, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.OrdersPageModel>>);

  @override
  _i3.Future<_i4.Result<_i8.OrderModel>> startOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue: _i3.Future<_i4.Result<_i8.OrderModel>>.value(
              _i7.dummyValue<_i4.Result<_i8.OrderModel>>(
                this,
                Invocation.method(#startOrder, [orderId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.OrderModel>>);

  @override
  _i3.Future<_i4.Result<_i8.OrderModel>> updateOrderState(
    String? orderId,
    String? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderState, [orderId, state]),
            returnValue: _i3.Future<_i4.Result<_i8.OrderModel>>.value(
              _i7.dummyValue<_i4.Result<_i8.OrderModel>>(
                this,
                Invocation.method(#updateOrderState, [orderId, state]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.OrderModel>>);
}

/// A class which mocks [TrackingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackingRepository extends _i1.Mock
    implements _i9.TrackingRepository {
  MockTrackingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addUser(_i10.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#addUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> addOrder(_i11.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#addOrder, [order]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addOrder, [order]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateOrder(_i11.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [order]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertOrder(String? orderId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertOrder, [orderId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i11.OrderEntity?> getOrderStream(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStream, [orderId]),
            returnValue: _i3.Stream<_i11.OrderEntity?>.empty(),
          )
          as _i3.Stream<_i11.OrderEntity?>);
}

/// A class which mocks [OrderTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingService extends _i1.Mock
    implements _i12.OrderTrackingService {
  MockOrderTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsertOrder(String? orderId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertOrder, [orderId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatus({
    required String? orderId,
    required String? status,
    String? driverId,
    double? lat,
    double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [], {
              #orderId: orderId,
              #status: status,
              #driverId: driverId,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDriverLocation({
    required String? orderId,
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDriverLocation, [], {
              #orderId: orderId,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<Map<String, dynamic>?> watchOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrder, [orderId]),
            returnValue: _i3.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>?>);

  @override
  _i3.Future<_i13.UserEntity?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i3.Future<_i13.UserEntity?>.value(),
          )
          as _i3.Future<_i13.UserEntity?>);

  @override
  _i3.Future<void> setUserOrder({
    required String? userId,
    required String? orderId,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserOrder, [], {
              #userId: userId,
              #orderId: orderId,
              #data: data,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyUser({
    required String? userId,
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyUser, [], {
              #userId: userId,
              #title: title,
              #body: body,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
