// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/features/driver_orders/presentation/cubit/driver_orders_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:track_flowers_app/config/base_response/entity/base_pagination_entity.dart'
    as _i5;
import 'package:track_flowers_app/config/base_response/result.dart' as _i4;
import 'package:track_flowers_app/config/uses_cases/pagination_params.dart'
    as _i7;
import 'package:track_flowers_app/config/uses_cases/use_cases.dart' as _i11;
import 'package:track_flowers_app/features/driver_orders/domain/entities/order_entity.dart'
    as _i6;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/accept_order_use_case.dart'
    as _i12;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/complete_order_use_case.dart'
    as _i15;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/get_active_order_use_case.dart'
    as _i10;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/get_my_orders_use_case.dart'
    as _i9;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/get_pending_orders_use_case.dart'
    as _i2;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/mirror_order_use_case.dart'
    as _i16;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/reject_order_use_case.dart'
    as _i13;
import 'package:track_flowers_app/features/driver_orders/domain/use_cases/start_order_use_case.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetPendingOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingOrdersUseCase extends _i1.Mock
    implements _i2.GetPendingOrdersUseCase {
  MockGetPendingOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>> call(
    _i7.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>>);
}

/// A class which mocks [GetMyOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyOrdersUseCase extends _i1.Mock
    implements _i9.GetMyOrdersUseCase {
  MockGetMyOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>> call(
    _i7.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.BasePaginationEntity<_i6.OrderEntity>>>);
}

/// A class which mocks [GetActiveOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveOrderUseCase extends _i1.Mock
    implements _i10.GetActiveOrderUseCase {
  MockGetActiveOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> call(_i11.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);
}

/// A class which mocks [AcceptOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAcceptOrderUseCase extends _i1.Mock
    implements _i12.AcceptOrderUseCase {
  MockAcceptOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> call(_i6.OrderEntity? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);
}

/// A class which mocks [RejectOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRejectOrderUseCase extends _i1.Mock
    implements _i13.RejectOrderUseCase {
  MockRejectOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> call(_i6.OrderEntity? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);
}

/// A class which mocks [StartOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartOrderUseCase extends _i1.Mock implements _i14.StartOrderUseCase {
  MockStartOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> call(_i6.OrderEntity? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);
}

/// A class which mocks [CompleteOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteOrderUseCase extends _i1.Mock
    implements _i15.CompleteOrderUseCase {
  MockCompleteOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i6.OrderEntity>> call(_i6.OrderEntity? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i6.OrderEntity>>.value(
              _i8.dummyValue<_i4.Result<_i6.OrderEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.OrderEntity>>);
}

/// A class which mocks [MirrorOrderUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMirrorOrderUseCase extends _i1.Mock
    implements _i16.MirrorOrderUseCase {
  MockMirrorOrderUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    _i6.OrderEntity? order, {
    double? driverLat,
    double? driverLng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [order],
              {#driverLat: driverLat, #driverLng: driverLng},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
