// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/features/driver_orders/data/data_sources/driver_orders_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:track_flowers_app/config/uses_cases/pagination_params.dart'
    as _i6;
import 'package:track_flowers_app/features/driver_orders/api/api_client/driver_orders_api_client.dart'
    as _i4;
import 'package:track_flowers_app/features/driver_orders/data/models/order_model.dart'
    as _i3;
import 'package:track_flowers_app/features/driver_orders/data/models/orders_page_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrdersPageModel_0 extends _i1.SmartFake
    implements _i2.OrdersPageModel {
  _FakeOrdersPageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderModel_1 extends _i1.SmartFake implements _i3.OrderModel {
  _FakeOrderModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DriverOrdersApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverOrdersApiClient extends _i1.Mock
    implements _i4.DriverOrdersApiClient {
  MockDriverOrdersApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.OrdersPageModel> getPendingOrders(
    _i6.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOrders, [params]),
            returnValue: _i5.Future<_i2.OrdersPageModel>.value(
              _FakeOrdersPageModel_0(
                this,
                Invocation.method(#getPendingOrders, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.OrdersPageModel>);

  @override
  _i5.Future<_i2.OrdersPageModel> getMyOrders(_i6.PaginationParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [params]),
            returnValue: _i5.Future<_i2.OrdersPageModel>.value(
              _FakeOrdersPageModel_0(
                this,
                Invocation.method(#getMyOrders, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.OrdersPageModel>);

  @override
  _i5.Future<_i3.OrderModel> startOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue: _i5.Future<_i3.OrderModel>.value(
              _FakeOrderModel_1(
                this,
                Invocation.method(#startOrder, [orderId]),
              ),
            ),
          )
          as _i5.Future<_i3.OrderModel>);

  @override
  _i5.Future<_i3.OrderModel> updateOrderState(
    String? orderId,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderState, [orderId, body]),
            returnValue: _i5.Future<_i3.OrderModel>.value(
              _FakeOrderModel_1(
                this,
                Invocation.method(#updateOrderState, [orderId, body]),
              ),
            ),
          )
          as _i5.Future<_i3.OrderModel>);
}
