// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/features/auth_module/presentation/view_model/auth_module_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:track_flowers_app/config/base_response/result.dart' as _i4;
import 'package:track_flowers_app/config/uses_cases/login_params.dart' as _i6;
import 'package:track_flowers_app/features/auth_module/domain/entities/driver_login_response_entity.dart'
    as _i5;
import 'package:track_flowers_app/features/auth_module/domain/repositories/auth_module_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthModuleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthModuleRepository extends _i1.Mock
    implements _i2.AuthModuleRepository {
  MockAuthModuleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.DriverLoginResponseEntity>> loginDriver(
    _i6.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginDriver, [params]),
            returnValue:
                _i3.Future<_i4.Result<_i5.DriverLoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.Result<_i5.DriverLoginResponseEntity>>(
                    this,
                    Invocation.method(#loginDriver, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.DriverLoginResponseEntity>>);

  @override
  _i3.Future<_i4.Result<void>> saveDriverToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveDriverToken, [token]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveDriverToken, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteDriverToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDriverToken, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteDriverToken, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveCredentials({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveCredentials, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCredentials, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteCredentials, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<Map<String, String?>>> getSavedCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedCredentials, []),
            returnValue: _i3.Future<_i4.Result<Map<String, String?>>>.value(
              _i7.dummyValue<_i4.Result<Map<String, String?>>>(
                this,
                Invocation.method(#getSavedCredentials, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, String?>>>);
}
