// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:track_flowers_app/config/base_response/result.dart' as _i7;
import 'package:track_flowers_app/config/uses_cases/use_cases.dart' as _i17;
import 'package:track_flowers_app/features/auth_module/api/api_client/auth_module_api_client.dart'
    as _i14;
import 'package:track_flowers_app/features/auth_module/data/datasources/auth_module_local_data_source_contract.dart'
    as _i13;
import 'package:track_flowers_app/features/auth_module/data/datasources/auth_module_remote_data_source_contract.dart'
    as _i12;
import 'package:track_flowers_app/features/auth_module/data/models/profile_model.dart'
    as _i2;
import 'package:track_flowers_app/features/auth_module/data/models/reset_password_response_model.dart'
    as _i4;
import 'package:track_flowers_app/features/auth_module/domain/entities/profile_response_entity.dart'
    as _i8;
import 'package:track_flowers_app/features/auth_module/domain/entities/reset_password_response_entity.dart'
    as _i11;
import 'package:track_flowers_app/features/auth_module/domain/repositories/auth_module_repository.dart'
    as _i5;
import 'package:track_flowers_app/features/auth_module/domain/use_cases/edit_profile_use_case.dart'
    as _i18;
import 'package:track_flowers_app/features/auth_module/domain/use_cases/get_profile_use_case.dart'
    as _i16;
import 'package:track_flowers_app/features/auth_module/domain/use_cases/reset_password_use_case.dart'
    as _i15;
import 'package:track_flowers_app/features/auth_module/domain/use_cases/update_profile_photo_use_case.dart'
    as _i19;
import 'package:track_flowers_app/features/login/data/models/login_response_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileModel_0 extends _i1.SmartFake implements _i2.ProfileModel {
  _FakeProfileModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseModel_1 extends _i1.SmartFake
    implements _i3.LoginResponseModel {
  _FakeLoginResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseModel {
  _FakeResetPasswordResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthModuleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthModuleRepository extends _i1.Mock
    implements _i5.AuthModuleRepository {
  MockAuthModuleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i8.ProfileResponseEntity>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue:
                _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.ProfileResponseEntity>>(
                    this,
                    Invocation.method(#getProfile, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>);

  @override
  _i6.Future<_i7.Result<_i8.ProfileResponseEntity>> editProfile(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [body]),
            returnValue:
                _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.ProfileResponseEntity>>(
                    this,
                    Invocation.method(#editProfile, [body]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>);

  @override
  _i6.Future<_i7.Result<_i8.ProfileResponseEntity>> updateProfilePhoto(
    _i10.File? file,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [file]),
            returnValue:
                _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.ProfileResponseEntity>>(
                    this,
                    Invocation.method(#updateProfilePhoto, [file]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>);

  @override
  _i6.Future<_i7.Result<_i11.ResetPasswordResponseEntity>> resetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue:
                _i6.Future<_i7.Result<_i11.ResetPasswordResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i11.ResetPasswordResponseEntity>>(
                    this,
                    Invocation.method(#resetPassword, [body]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i11.ResetPasswordResponseEntity>>);
}

/// A class which mocks [AuthModuleRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthModuleRemoteDataSourceContract extends _i1.Mock
    implements _i12.AuthModuleRemoteDataSourceContract {
  MockAuthModuleRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i3.LoginResponseModel>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<_i7.Result<_i3.LoginResponseModel>>.value(
              _i9.dummyValue<_i7.Result<_i3.LoginResponseModel>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i3.LoginResponseModel>>);

  @override
  _i6.Future<_i7.Result<_i3.LoginResponseModel>> editProfile(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [body]),
            returnValue: _i6.Future<_i7.Result<_i3.LoginResponseModel>>.value(
              _i9.dummyValue<_i7.Result<_i3.LoginResponseModel>>(
                this,
                Invocation.method(#editProfile, [body]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i3.LoginResponseModel>>);

  @override
  _i6.Future<_i7.Result<_i3.LoginResponseModel>> updateProfilePhoto(
    _i10.File? file,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [file]),
            returnValue: _i6.Future<_i7.Result<_i3.LoginResponseModel>>.value(
              _i9.dummyValue<_i7.Result<_i3.LoginResponseModel>>(
                this,
                Invocation.method(#updateProfilePhoto, [file]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i3.LoginResponseModel>>);

  @override
  _i6.Future<_i7.Result<_i4.ResetPasswordResponseModel>> resetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue:
                _i6.Future<_i7.Result<_i4.ResetPasswordResponseModel>>.value(
                  _i9.dummyValue<_i7.Result<_i4.ResetPasswordResponseModel>>(
                    this,
                    Invocation.method(#resetPassword, [body]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i4.ResetPasswordResponseModel>>);
}

/// A class which mocks [AuthModuleLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthModuleLocalDataSourceContract extends _i1.Mock
    implements _i13.AuthModuleLocalDataSourceContract {
  MockAuthModuleLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ProfileModel> saveProfile(_i2.ProfileModel? profileModel) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profileModel]),
            returnValue: _i6.Future<_i2.ProfileModel>.value(
              _FakeProfileModel_0(
                this,
                Invocation.method(#saveProfile, [profileModel]),
              ),
            ),
          )
          as _i6.Future<_i2.ProfileModel>);

  @override
  _i6.Future<_i2.ProfileModel?> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<_i2.ProfileModel?>.value(),
          )
          as _i6.Future<_i2.ProfileModel?>);
}

/// A class which mocks [AuthModuleApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthModuleApiClient extends _i1.Mock
    implements _i14.AuthModuleApiClient {
  MockAuthModuleApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.LoginResponseModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<_i3.LoginResponseModel>.value(
              _FakeLoginResponseModel_1(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponseModel>);

  @override
  _i6.Future<_i3.LoginResponseModel> editProfile(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [body]),
            returnValue: _i6.Future<_i3.LoginResponseModel>.value(
              _FakeLoginResponseModel_1(
                this,
                Invocation.method(#editProfile, [body]),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponseModel>);

  @override
  _i6.Future<_i3.LoginResponseModel> updateProfilePhoto(_i10.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [file]),
            returnValue: _i6.Future<_i3.LoginResponseModel>.value(
              _FakeLoginResponseModel_1(
                this,
                Invocation.method(#updateProfilePhoto, [file]),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponseModel>);

  @override
  _i6.Future<_i4.ResetPasswordResponseModel> resetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue: _i6.Future<_i4.ResetPasswordResponseModel>.value(
              _FakeResetPasswordResponseModel_2(
                this,
                Invocation.method(#resetPassword, [body]),
              ),
            ),
          )
          as _i6.Future<_i4.ResetPasswordResponseModel>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i15.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i11.ResetPasswordResponseEntity>> call(
    Map<String, dynamic>? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i7.Result<_i11.ResetPasswordResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i11.ResetPasswordResponseEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i11.ResetPasswordResponseEntity>>);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i16.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i8.ProfileResponseEntity>> call(
    _i17.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.ProfileResponseEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i18.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i8.ProfileResponseEntity>> call(
    Map<String, dynamic>? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.ProfileResponseEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>);
}

/// A class which mocks [UpdateProfilePhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfilePhotoUseCase extends _i1.Mock
    implements _i19.UpdateProfilePhotoUseCase {
  MockUpdateProfilePhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i8.ProfileResponseEntity>> call(_i10.File? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.ProfileResponseEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.ProfileResponseEntity>>);
}
