// Mocks generated by Mockito 5.4.6 from annotations
// in track_flowers_app/test/features/profile/presentation/view_model/cubit/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:track_flowers_app/config/base_response/result.dart' as _i4;
import 'package:track_flowers_app/config/uses_cases/use_cases.dart' as _i6;
import 'package:track_flowers_app/features/login/domain/entities/user_entity.dart'
    as _i5;
import 'package:track_flowers_app/features/login/domain/use_cases/save_user_use_case.dart'
    as _i8;
import 'package:track_flowers_app/features/profile/data/models/change_password_request_model.dart'
    as _i15;
import 'package:track_flowers_app/features/profile/data/models/edit_profile_request_model.dart'
    as _i10;
import 'package:track_flowers_app/features/profile/domain/use_cases/change_password_use_case.dart'
    as _i14;
import 'package:track_flowers_app/features/profile/domain/use_cases/edit_profile_use_case.dart'
    as _i9;
import 'package:track_flowers_app/features/profile/domain/use_cases/get_profile_use_case.dart'
    as _i2;
import 'package:track_flowers_app/features/profile/domain/use_cases/logout_use_case.dart'
    as _i13;
import 'package:track_flowers_app/features/profile/domain/use_cases/upload_profile_photo_use_case.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i2.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserEntity>> call(_i6.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.UserEntity>>.value(
              _i7.dummyValue<_i4.Result<_i5.UserEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserEntity>>);
}

/// A class which mocks [SaveUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveUserUseCase extends _i1.Mock implements _i8.SaveUserUseCase {
  MockSaveUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserEntity>> call(_i5.UserEntity? userEntity) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userEntity]),
            returnValue: _i3.Future<_i4.Result<_i5.UserEntity>>.value(
              _i7.dummyValue<_i4.Result<_i5.UserEntity>>(
                this,
                Invocation.method(#call, [userEntity]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserEntity>>);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i9.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserEntity>> call(
    _i10.EditProfileRequestModel? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.UserEntity>>.value(
              _i7.dummyValue<_i4.Result<_i5.UserEntity>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserEntity>>);
}

/// A class which mocks [UploadProfilePhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfilePhotoUseCase extends _i1.Mock
    implements _i11.UploadProfilePhotoUseCase {
  MockUploadProfilePhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<String>> call(_i12.File? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i13.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> call(_i6.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i14.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> call(_i15.ChangePasswordRequestModel? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
